clc;
clear all;
close all;
m = 18;
Tot_bits = ((2^18)-1);
num_bits = 8100005;
frame_bits = 8100;
frames = floor(((num_bits)/2)/frame_bits);
e = 0.05;
[Iscr_Qscr,z,C_scrambled,complex_bits,bits] = DVBS2(Tot_bits,num_bits,frame_bits,frames,e,m);
New_Iscr_Qscr = reshape(Iscr_Qscr,frames,frame_bits);
F1 = real(New_Iscr_Qscr);
F2 = imag(New_Iscr_Qscr);
F = F1.*F2;
Xj = sum(F);
out = ~(Xj>0);
final = sum(xor(z(1:frame_bits),out));
Input_seq = New_Iscr_Qscr./C_scrambled;
x1 = reshape(real(Input_seq),1,(frame_bits*frames));
x2 = reshape(imag(Input_seq),1,(frame_bits*frames));
message = [x1,x2];
last = sum(xor(bits(1:(frame_bits*frames*2)),message));